### ISSUE TITLE
Is it possible to get access to the OHNN model?

### ISSUE THREAD

**Issue by unilight** [nii-yamagishilab/SSL-SAS#2]
Hi @xiaoxiaomiao39, thanks for this great project!

I am wondering if it is possible to have access to the OHNN model?
I just want to use the trained model weights to run inference on some custom dataset.
Thank you!

**Comment by xiaoxiaomiao323** [comment]
Hi @unilight , sorry, I lost access to the xiaoxiaomiao39 account and just noticed your message. Unfortunately, we currently don't have any plans to release OHNN, as we are in the process of applying for a patent. 
Thanks!

**Comment by unilight** [comment]
@xiaoxiaomiao323 no problem, thanks for the reply!
BTW can you kindly tell me which method (or paper) the pre-trained model refers to?

**Comment by unilight** [comment]
Much thanks!!
